version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432

  backend:
    env_file:
      - .env
    build:
      context: ./backend
      args:
        SECRET_KEY: ${SECRET_KEY}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./backend:/backend
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - 80:80
    depends_on:
      - backend