name: 'Backend deploy'
on:
  push:
    branches:
      - main
      - setup_ci
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy Docker Image to Heroku
        uses: techmmunity/docker-heroku-deploy@v1.0.0
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_path: ''
          dockerfile_name: 'Dockerfile.heroku'